stages:
  - setup
  - build
  - test

setup_job:
  stage: setup
  script:
    - ssh root@172.16.39.69 "ansible-playbook -i hosts ubuntu_test.yaml --ssh-common-args='-o StrictHostKeyChecking=no'"

build_job:
  stage: build
  script:
    - apt-get update
    - apt-get install -y wget curl
    - mkdir /etc/pihole
    - wget -O /etc/pihole/setupVars.conf https://pastebin.com/raw/YBpWALGg
    - curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash -s -- --unattended
