- name: Verwijder de oude TestVM
  hosts:
    - pm03
  tasks:
    - name: Controleer of VM bestaat
      command: qm status 6970
      register: vm_status
      ignore_errors: true

    - name: Stop en vernietig VM
      shell: |
        qm stop 6970
        qm destroy 6970
      when: vm_status.rc == 0



- name: maak TestVM
  hosts: localhost
  gather_facts: no
  become: yes

  vars:
    pm03: 172.16.39.72
    node3: geenboom4
    api_password: "{{ lookup('file', '/home/geenboom1/ansible_wordpress_project/Devsecops/kak.txt') }}"

  tasks:

    - name: Create VMs on pm03
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ api_password }}"
        api_host: "{{ pm03 }}"
        node: "{{ node3 }}"
        name: "{{ item.hostname }}"
        clone: "{{ item.template }}"
        newid: "{{ item.vmid }}"
        memory: 2048
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
        ipconfig: '{"net0":"ip={{ item.ip }}/16,gw=172.16.0.1"}'
        agent: '1'
        timeout: 300
      loop:
        - { template: "ubuntu-2004-cloudinit-template3", vmid: 6970, hostname: "DevSecOpsTest", ip: "172.16.39.124" }

###
### ips toevoegen aan de VMs
###

- name: Voeg shared_storage toe aan Proxmox03
  hosts:
    - pm03
  tasks:
    - name: toevoegen....
      shell: |
        qm set 6970 --virtio0 shared_storage:50,format=qcow2
        qm set 6970 --ipconfig0 ip=172.16.39.124/16,gw=172.16.0.1
        qm set 6970 --sshkey /root/.ssh/id_rsa.pub

- name: VM starten op Proxmox 3
  hosts: pm03
  tasks:
    - name: Start VM on pm03
      shell: "qm status 6970 | grep -q 'status: running' || qm start 6970"

    - name: wachten op volledige boot zodat wij de cli kunnen gebruiken(80 seconden...)
      pause:
        seconds: 80

###
### monitoring toevoegen
###
- name: Voeg shared_storage toe aan Proxmox03
  hosts: localhost
  tasks:
    - name: ssh key refreshen
      ansible.builtin.shell: ssh-keygen -f "/root/.ssh/known_hosts" -R "172.16.39.124"

- name: monitoring toevoegen aan de testserver
  hosts: DevSecOpsTest
  tasks:

    - name: monitor server toevoegen(netdata)
      ansible.builtin.shell: wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --nightly-channel --claim-token ZrQ5HQusgHQrZ5ZFxOIC2qgDj3w0bmLNyJMipriRpEJ6ryTNmu66ENNTUQHHXaLf0UU_wBv7T6QaHXJ1FpA7iLRM67wZXCrn_Tz7hsZhRMvByX027oFzczqEju3-Ew2bOzIOxxM --claim-rooms 25a63be6-ad65-4774-9334-3e6790f92a9f --claim-url https://app.netdata.cloud

###
### shared storage toevoegen
###

- name: de VDA opslag gebruiken
  hosts: DevSecOpsTest
  become: yes
  tasks:
    - name: Maak het mount point
      file:
        path: /mnt/vda
        state: directory
    ###
    ### verander het bestandtype van vda naar ext4
    ###
    - name: verander het bestandstype van vda naar ext4
      shell: mkfs.ext4 /dev/vda

    - name: Voeg de harde schijf toe aan /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: '/dev/vda /mnt/vda ext4 defaults 0 0'
        state: present

    - name: Mount alle bestandssystemen waarvan de fstab regels gelezen zijn
      command:
        cmd: mount -a

